import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm,readFile,writeFile,readdir} from 'node:fs/promises';import {join,resolve,sep} from 'node:path';import {tmpdir} from 'node:os';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {spawn} from 'node:child_process';
const moduleUrl=pathToFileURL(join(process.env.TARGET_CWD,'jobs.mjs')).href;const {claimJob,readJob,finishJob}=await import(moduleUrl);const recordPath=(dir,id)=>join(dir,createHash('sha256').update(id).digest('hex')+'.json');
async function fixture(fn){const base=resolve(tmpdir()),dir=await mkdtemp(join(base,'dsh-jobs-'));try{await fn(dir);}finally{if(!dir.startsWith(base+sep)||!dir.slice(base.length+1).startsWith('dsh-jobs-'))throw Error('Cleanup boundary');await rm(dir,{recursive:true});}}
function worker(dir,method,id,value){return new Promise((done,fail)=>{const source="const m=await import(process.argv[1]);try{const r=await m[process.argv[2]](process.argv[3],process.argv[4],JSON.parse(process.argv[5]));console.log(JSON.stringify({ok:true,value:r}));}catch(e){console.log(JSON.stringify({ok:false,code:e.code}));}";const c=spawn(process.execPath,['--input-type=module','-e',source,moduleUrl,method,dir,id,JSON.stringify(value)],{windowsHide:true});let out='';c.stdout.on('data',d=>out+=d);const timer=setTimeout(()=>{c.kill();fail(Error('Worker timeout'));},10000);c.on('error',fail);c.on('close',code=>{clearTimeout(timer);try{if(code!==0)throw Error('Worker failed');done(JSON.parse(out.trim()));}catch(e){fail(e);}});});}
test('durable intent, canonical replay and returned copies',()=>fixture(async dir=>{assert.equal(await readJob(dir,'x'),null);assert.deepEqual(await readdir(dir),[]);const first=await claimJob(dir,'x',{z:[1,2],a:{b:1,c:2}});assert.equal(first.created,true);first.record.payload.z[0]=99;assert.equal((await claimJob(dir,'x',{a:{c:2,b:1},z:[1,2]})).created,false);assert.equal((await readJob(dir,'x')).payload.z[0],1);assert.equal((await worker(dir,'claimJob','x',{z:[1,2],a:{b:1,c:2}})).value.created,false);assert.equal(JSON.parse(await readFile(recordPath(dir,'x'),'utf8')).state,'pending');}));
test('special identifiers and object keys stay safe',()=>fixture(async dir=>{for(const id of ['constructor','__proto__','../escape','中文/任务']){await claimJob(dir,id,JSON.parse('{"__proto__":{"flag":1},"constructor":"own"}'));const r=await readJob(dir,id);assert.equal(r.id,id);assert.equal(Object.hasOwn(r.payload,'__proto__'),true);assert.equal(r.payload.constructor,'own');assert.equal((await claimJob(dir,id,r.payload)).created,false);}assert.equal(({}).flag,undefined);assert.equal((await readdir(dir)).filter(n=>n.endsWith('.json')).length,4);}));
test('invalid inputs do not leave receipts',()=>fixture(async dir=>{const cyclic={};cyclic.self=cyclic;for(const value of [undefined,NaN,Infinity,{x:undefined},[()=>{}],new Date(),cyclic])await assert.rejects(()=>claimJob(dir,'bad',value),{code:'INVALID_INPUT'});assert.equal(await readJob(dir,'bad'),null);await assert.rejects(()=>claimJob(dir,'',{}),{code:'INVALID_INPUT'});}));
test('conflicts and completion preserve the committed value',()=>fixture(async dir=>{await claimJob(dir,'x',{a:1});const before=await readFile(recordPath(dir,'x'),'utf8');await assert.rejects(()=>claimJob(dir,'x',{a:2}),{code:'JOB_CONFLICT'});assert.equal(await readFile(recordPath(dir,'x'),'utf8'),before);await assert.rejects(()=>finishJob(dir,'nope',null),{code:'JOB_UNKNOWN'});await finishJob(dir,'x',{a:1,b:2});await finishJob(dir,'x',{b:2,a:1});await assert.rejects(()=>finishJob(dir,'x',{a:3}),{code:'JOB_CONFLICT'});assert.equal((await readJob(dir,'x')).result.a,1);assert.equal((await claimJob(dir,'x',{a:1})).record.state,'completed');}));
test('six processes claim exactly once',()=>fixture(async dir=>{const rows=await Promise.all(Array.from({length:6},()=>worker(dir,'claimJob','race',{x:1})));assert.equal(rows.filter(r=>r.ok&&r.value.created).length,1);assert.equal(rows.filter(r=>r.ok).length,6);assert.equal((await readJob(dir,'race')).state,'pending');}));
test('conflicting completions have one durable winner',()=>fixture(async dir=>{await claimJob(dir,'race',{});const rows=await Promise.all([worker(dir,'finishJob','race',{winner:'a'}),worker(dir,'finishJob','race',{winner:'b'})]);assert.equal(rows.filter(r=>r.ok).length,1);assert.equal(rows.filter(r=>!r.ok&&r.code==='JOB_CONFLICT').length,1);const winner=rows.find(r=>r.ok).value.result;assert.deepEqual((await readJob(dir,'race')).result,winner);}));
test('corruption remains visible and never gets replaced',()=>fixture(async dir=>{await claimJob(dir,'x',{});await writeFile(recordPath(dir,'x'),'{broken');await assert.rejects(()=>readJob(dir,'x'),{code:'JOB_CORRUPT'});await assert.rejects(()=>claimJob(dir,'x',{}),{code:'JOB_CORRUPT'});await assert.rejects(()=>finishJob(dir,'x',null),{code:'JOB_CORRUPT'});assert.equal(await readFile(recordPath(dir,'x'),'utf8'),'{broken');}));
test('bounded reader sampling around an update sees valid snapshots',()=>fixture(async dir=>{await claimJob(dir,'x',{});let finished=false,samples=0;const finish=worker(dir,'finishJob','x',{blob:'x'.repeat(16000)}).finally(()=>{finished=true;});while(!finished&&samples<2000){const r=await readJob(dir,'x');assert.ok(r.state==='pending'||r.state==='completed');samples++;}await finish;assert.ok(samples>0);assert.equal((await readJob(dir,'x')).result.blob.length,16000);}));